// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ICommand is an autogenerated mock type for the ICommand type
type ICommand struct {
	mock.Mock
}

// CI provides a mock function with given fields:
func (_m *ICommand) CI() {
	_m.Called()
}

// Create provides a mock function with given fields: language, name
func (_m *ICommand) Create(language string, name string) {
	_m.Called(language, name)
}

// Enter provides a mock function with given fields:
func (_m *ICommand) Enter() {
	_m.Called()
}

// Install provides a mock function with given fields:
func (_m *ICommand) Install() {
	_m.Called()
}

// Run provides a mock function with given fields: args, imageOnly
func (_m *ICommand) Run(args []string, imageOnly bool) {
	_m.Called(args, imageOnly)
}

// Stage provides a mock function with given fields: stage, imageOnly
func (_m *ICommand) Stage(stage string, imageOnly bool) {
	_m.Called(stage, imageOnly)
}

// Verify provides a mock function with given fields:
func (_m *ICommand) Verify() {
	_m.Called()
}
