// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ICommand is an autogenerated mock type for the ICommand type
type ICommand struct {
	mock.Mock
}

// CI provides a mock function with given fields: cmds
func (_m *ICommand) CI(cmds []string) {
	_m.Called(cmds)
}

// Create provides a mock function with given fields: name, language
func (_m *ICommand) Create(name string, language string) {
	_m.Called(name, language)
}

// Enter provides a mock function with given fields:
func (_m *ICommand) Enter() {
	_m.Called()
}

// Install provides a mock function with given fields:
func (_m *ICommand) Install() {
	_m.Called()
}

// Language provides a mock function with given fields: cmds, imageOnly
func (_m *ICommand) Language(cmds []string, imageOnly bool) {
	_m.Called(cmds, imageOnly)
}

// Run provides a mock function with given fields: args, imageOnly
func (_m *ICommand) Run(args []string, imageOnly bool) {
	_m.Called(args, imageOnly)
}
