// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// IDevelop is an autogenerated mock type for the IDevelop type
type IDevelop struct {
	mock.Mock
}

// Enter provides a mock function with given fields:
func (_m *IDevelop) Enter() {
	_m.Called()
}

// Install provides a mock function with given fields:
func (_m *IDevelop) Install() {
	_m.Called()
}

// Login provides a mock function with given fields:
func (_m *IDevelop) Login() {
	_m.Called()
}

// Run provides a mock function with given fields: args, imageOnly
func (_m *IDevelop) Run(args []string, imageOnly bool) {
	_m.Called(args, imageOnly)
}

// Stage provides a mock function with given fields: stage, imageOnly
func (_m *IDevelop) Stage(stage string, imageOnly bool) {
	_m.Called(stage, imageOnly)
}

// Upload provides a mock function with given fields:
func (_m *IDevelop) Upload() {
	_m.Called()
}
