// Code generated by mockery v1.0.0
package mocks

import meta "meta/meta"
import mock "github.com/stretchr/testify/mock"

// IDotMeta is an autogenerated mock type for the IDotMeta type
type IDotMeta struct {
	mock.Mock
}

// MoveToRoot provides a mock function with given fields:
func (_m *IDotMeta) MoveToRoot() {
	_m.Called()
}

// ReadMetaYml provides a mock function with given fields:
func (_m *IDotMeta) ReadMetaYml() *meta.MetaYml {
	ret := _m.Called()

	var r0 *meta.MetaYml
	if rf, ok := ret.Get(0).(func() *meta.MetaYml); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.MetaYml)
		}
	}

	return r0
}
