// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ILog is an autogenerated mock type for the ILog type
type ILog struct {
	mock.Mock
}

// Fatal provides a mock function with given fields: v
func (_m *ILog) Fatal(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Fatalf provides a mock function with given fields: format, v
func (_m *ILog) Fatalf(format string, v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Println provides a mock function with given fields: v
func (_m *ILog) Println(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}
