// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// IRelease is an autogenerated mock type for the IRelease type
type IRelease struct {
	mock.Mock
}

// Create provides a mock function with given fields: newVersion, message
func (_m *IRelease) Create(newVersion string, message string) {
	_m.Called(newVersion, message)
}

// List provides a mock function with given fields:
func (_m *IRelease) List() {
	_m.Called()
}

// Unreleased provides a mock function with given fields:
func (_m *IRelease) Unreleased() {
	_m.Called()
}
