// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ISetup is an autogenerated mock type for the ISetup type
type ISetup struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *ISetup) Run() {
	_m.Called()
}
