// Code generated by mockery v1.0.0
package mocks

import meta "meta/meta"
import mock "github.com/stretchr/testify/mock"

// ISettings is an autogenerated mock type for the ISettings type
type ISettings struct {
	mock.Mock
}

// ReadCreateYml provides a mock function with given fields:
func (_m *ISettings) ReadCreateYml() *meta.CreateYml {
	ret := _m.Called()

	var r0 *meta.CreateYml
	if rf, ok := ret.Get(0).(func() *meta.CreateYml); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.CreateYml)
		}
	}

	return r0
}

// ReadLanguageYml provides a mock function with given fields: language
func (_m *ISettings) ReadLanguageYml(language string) *meta.LanguageYml {
	ret := _m.Called(language)

	var r0 *meta.LanguageYml
	if rf, ok := ret.Get(0).(func(string) *meta.LanguageYml); ok {
		r0 = rf(language)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.LanguageYml)
		}
	}

	return r0
}

// ReadVerifyYml provides a mock function with given fields:
func (_m *ISettings) ReadVerifyYml() *meta.VerifyYml {
	ret := _m.Called()

	var r0 *meta.VerifyYml
	if rf, ok := ret.Get(0).(func() *meta.VerifyYml); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meta.VerifyYml)
		}
	}

	return r0
}

// Translation provides a mock function with given fields: metaYml
func (_m *ISettings) Translation(metaYml *meta.MetaYml) interface{} {
	ret := _m.Called(metaYml)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(*meta.MetaYml) interface{}); ok {
		r0 = rf(metaYml)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
