// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ITemplate is an autogenerated mock type for the ITemplate type
type ITemplate struct {
	mock.Mock
}

// Create provides a mock function with given fields: name, language
func (_m *ITemplate) Create(name string, language string) {
	_m.Called(name, language)
}
