// Code generated by mockery v1.0.0
package mocks

import meta "meta/meta"
import mock "github.com/stretchr/testify/mock"

// ITemplate is an autogenerated mock type for the ITemplate type
type ITemplate struct {
	mock.Mock
}

// Create provides a mock function with given fields: metaYml
func (_m *ITemplate) Create(metaYml *meta.MetaYml) {
	_m.Called(metaYml)
}
