// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ITemplate is an autogenerated mock type for the ITemplate type
type ITemplate struct {
	mock.Mock
}

// ExecuteOnFile provides a mock function with given fields: sourcePath, targetPath, translation
func (_m *ITemplate) ExecuteOnFile(sourcePath string, targetPath string, translation interface{}) {
	_m.Called(sourcePath, targetPath, translation)
}

// ExecuteOnString provides a mock function with given fields: input, translation
func (_m *ITemplate) ExecuteOnString(input string, translation interface{}) string {
	ret := _m.Called(input, translation)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, interface{}) string); ok {
		r0 = rf(input, translation)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
