// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// IVerify is an autogenerated mock type for the IVerify type
type IVerify struct {
	mock.Mock
}

// Files provides a mock function with given fields:
func (_m *IVerify) Files() {
	_m.Called()
}
