// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// ILanguage is an autogenerated mock type for the ILanguage type
type ILanguage struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *ILanguage) Build() {
	_m.Called()
}

// CI provides a mock function with given fields:
func (_m *ILanguage) CI() {
	_m.Called()
}

// Coverage provides a mock function with given fields:
func (_m *ILanguage) Coverage() {
	_m.Called()
}

// Enter provides a mock function with given fields:
func (_m *ILanguage) Enter() {
	_m.Called()
}

// Install provides a mock function with given fields:
func (_m *ILanguage) Install() {
	_m.Called()
}

// Lint provides a mock function with given fields:
func (_m *ILanguage) Lint() {
	_m.Called()
}

// Run provides a mock function with given fields: args
func (_m *ILanguage) Run(args []string) {
	_m.Called(args)
}

// SetImageOnly provides a mock function with given fields:
func (_m *ILanguage) SetImageOnly() {
	_m.Called()
}

// Test provides a mock function with given fields:
func (_m *ILanguage) Test() {
	_m.Called()
}
