// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Language is an autogenerated mock type for the Language type
type Language struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *Language) Build() {
	_m.Called()
}

// CI provides a mock function with given fields:
func (_m *Language) CI() {
	_m.Called()
}

// Coverage provides a mock function with given fields:
func (_m *Language) Coverage() {
	_m.Called()
}

// Install provides a mock function with given fields:
func (_m *Language) Install() {
	_m.Called()
}

// Lint provides a mock function with given fields:
func (_m *Language) Lint() {
	_m.Called()
}

// Run provides a mock function with given fields:
func (_m *Language) Run() {
	_m.Called()
}

// Test provides a mock function with given fields:
func (_m *Language) Test() {
	_m.Called()
}
