stages:
  test:
    - nosestests test

  lint:
    - flake8 setup.py test {{:Name}}

  coverage:
    - nosestests --with-coverage test

  ci:
    - flake8 setup.py test {{:Name}}
    - nosestests --with-coverage test
