stages:
  test:
    - nosetests test

  lint:
    - flake8 setup.py test {{.Name}}

  coverage:
    - nosetests --with-coverage test

  ci:
    - flake8 setup.py test {{.Name}}
    - nosetests --with-coverage test

volumes:
  - "{{.Root}}/{{.Name}}:/usr/src/{{.Name}}/{{.Name}}"
  - "{{.Root}}/test:/usr/src/{{.Name}}/test"
